### ISSUE TITLE
v0.1.1版本无法使用

### ISSUE THREAD

**Issue by CattusFatalis** [XiYang6666/WrittenBookEditor#2]
v0.1.1版本生成的数据包没有作用

**Comment by XiYang6666** [comment]
能否提供minecraft版本？

**Comment by CattusFatalis** [comment]
Minecraft版本1.20.1
Forge版本47.3.11

**Comment by XiYang6666** [comment]
已成功复现，将在下个版本修复

**Comment by XiYang6666** [comment]
https://github.com/XiYang6666/WrittenBookEditor/releases/tag/v0.1.2
已修复
